workflows:
  android-dev:
    name: Android Dev
    triggering:
      cancel_previous_builds: true
      events:
        - push
      branch_patterns:
        - pattern: "master"
          include: true
          source: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build obfuscated apk
        script: |
          flutter build apk  --split-per-abi --obfuscate --split-debug-info=debug\
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        notify:
          success: true
          failure: false
        recipients:
          - mohamad.samer.abdulaziz@gmail.com



